### ISSUE TITLE
Drop support for legacy Blueprint theme for Bigcommerce

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-bigcommerce#45]
As of January 2018 blueprint themes have been deprecated - no one can create a new store with a blueprint theme. It would reduce testing by half if we could stop supporting these. 

However I'm not sure how we could do it without getting existing customers to modify their google analytics code. It would be worth seeing how many customers are using the blueprint theme.

**Comment by 1mattramsay** [comment]
Actions:
Edit this page: https://addressfinder.com.au/docs/plugins/bigcommerce_instructions_for_other_themes/

Replace the first block (What is the AddressFinder BigCommerce plugin?...) with "As BigCommerce no longer supports BluePrint themes, we have also our support for the AddressFinder-BluePrint plugin. 

If you still use a blueprint theme, you are welcome to follow the integration instructions below and test the plugin. If things work as expected then feel free to use the plugin however, if testing reveals issues we suggest you remove it as we are not in a position to resolve these."
