### ISSUE TITLE
Update BigCommerce plugin to webpage_tools v1.8.2

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-bigcommerce#47]

**Comment by caasssandre** [comment]
For now testing is inconclusive,
This spreadsheets shows the result of testing.

[BigCommerce checkouts - Sheet1.pdf](https://github.com/abletech/addressfinder-bigcommerce/files/4777752/BigCommerce.checkouts.-.Sheet1.pdf)

or here https://docs.google.com/spreadsheets/d/1vRmzErBqnBZ5LSZV6Vj9vpQ4u5y_LCdXiziSUzPnGHs/edit#gid=0
