### ISSUE TITLE
Drop support for legacy Blueprint and one page checkout for Bigcommerce

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-bigcommerce#52]
Bigcommerce has deprecated the Blueprint theme (no new stores can use it from November 2016) and the one page checkout (no new stores from May 2019).

We are going to remove the config files for these themes/checkout and no longer support them. This will mean we no longer need to test the plugin on these configurations when we make changes 🎉 .

We are going to create a new v2 of the bigcommerce plugin, accessible at 'https://api.addressfinder.io/assets/bigcommerce/v2/boot.js'. We will update our website to encourage new users to use the v2. Legacy users can continue to use v1, but there will be no updates to this file in the future, except in the case of severe bugs.

**Comment by 1mattramsay** [comment]
testing: 

Added the v2 plugin to the store and checked functionality when using the standard and recommended	
Optimized one-page checkout.

Switched to the non-optimised 'one page checkout'. The plugin loaded on the page but failed to work. 

Switched back to Optimised and the functionality returned - great.
