### ISSUE TITLE
Update website to reflect dropped support for blueprint theme and one page checkout for Bigcommerce

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-bigcommerce#53]
We need to update the website to indicate that new customers should be using the v2 Bigcommerce plugin:
`https://api.addressfinder.io/assets/bigcommerce/v2/boot.js`

If customers are using the blueprint theme or the one page checkout they should be directed to use the v1 plugin.

**Comment by 1mattramsay** [comment]
Here is am @caasssandre

**Comment by 1mattramsay** [comment]
Page edits and new link to the older v1 instructions looks excellent. Ready for prod.
