### ISSUE TITLE
Mutation issue on Bigcommerce Express Checkout

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-bigcommerce#54]
Widget is closing immediately after key presses on the express checkout. This checkout type is deprecated, but it would be good to fix this before we drop support for the blueprint theme and express checkout

TO TEST:
Once the changes are merged to staging, change your hosts file to point to staging and visit our BigCommerce customer websites - particularly those using the express checkout:
https://mycasecovers.com.au/checkout.php
https://www.healygroup.com.au/checkout.php

Optimised one page checkout example:
https://megaofficesupplies.com.au/checkout

**Comment by 1mattramsay** [comment]
Testing:
 
https://mycasecovers.com.au/checkout.php - works perfectly when adding an address and then changing this address for another.
https://www.healygroup.com.au/checkout.php - works perfectly when adding an address and then changing this address for another. 

https://megaofficesupplies.com.au/checkout - (optimised checkout) continues to work perfectly.
https://redsbaby.com.au/checkout - (optimised checkout) continues to work perfectly.

Ready for prod.
